version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: html_server
    ports:
      - "8765:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
    restart: always
